### ISSUE TITLE
Bitcoin Second Password recovery

### ISSUE THREAD

**Issue by onoja5** [gurnec/Undo_MoM2e#1]
Hello Gurnec,
Thanks alot for the documentation on how to recover second password on block-chain,
I follow through but when I insert my wallet ID I don't received verification email for me to proceed when I clicked on download-blockchain-wallet. 
Please I will appreciate if you can help, I don't mind paying for this service service please.
onoja16@gmail.com
God Bless.
Thank You.

**Comment by gurnec** [comment]
> when I insert my wallet ID I don't received verification email

I have no way to troubleshoot this... it could be that Blockchain has the wrong email for you, or your email provider is rejecting it as spam, or I don't know what....

You should to contact Blockchain if you think your verification email isn't getting to you, but regardless please be sure to open any future btcrecover-related tickets in the right repo (the right project; this project isn't related to Bitcoin)...
